### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by vipien** [acorcutt/next-multi-host#4]
I would like to know if this approach is working? Or do you know any limitations?

Because I need to start working on a website where the domain will be a workspace and based on the domain we will create static content.

I know it is possible with SSR but I prefer to have SSG.

Thanks in advance.

**Comment by acorcutt** [comment]
Hi, the simple routes seem to be working ok so no problem with `/:host/posts/:id/comments/:cid` but there are issues with wildcards when they overlap with other routes such as `/:host/posts/[...path]` and `:host/posts/:id` together.

The example https://next-multi-host.vercel.app/ falls back to SSR for the `/[...path]` route.

It gets a little complicated if you need to use additional headers and cookies as you need a rewrite for every combination and create quite deep paths `/:host/:location/:auth_cookie/posts/:id` Maybe combining the headers into a single path is easier - checkout the `/pages/headers/[...headers]` page for example, using a regex rewrite might also help.

**Comment by vipien** [comment]
Thanks for your answer. I will look at it.
