### ISSUE TITLE
Test different hosts in locale environment

### ISSUE THREAD

**Issue by izziaraffaele** [acorcutt/next-multi-host#6]
How do you test different host in development mode with this setup? Would be nice to add a URL param (like next is doing for i18n support) to switch from one host to the other

**Comment by acorcutt** [comment]
On macOS you can just use a subdomain to localhost e.g. `http://a.localhost:3000/` `http://b.localhost:3000/` or add domains to your /etc/hosts file.

I'm not sure about automated testing but the standard routes will be still be available. So if you are redirecting to  `/:host/page.js` the path `/my.host.com/page` should work.

**Comment by izziaraffaele** [comment]
`I'm not sure about automated testing but the standard routes will be still be available. So if you are redirecting to /:host/page.js the path /my.host.com/page should work.`

I'm not sure this will work with links in the page. For example, the `href` attribute will point to `/page-2` and the `:host` parameter will be lost

**Comment by acorcutt** [comment]
Maybe [next-page-tester](https://github.com/toomuchdesign/next-page-tester) could work, there is an [example testing cookies](https://github.com/toomuchdesign/next-page-tester#how-do-i-make-cookies-available-in-nextjs-data-fetching-methods) so could this be modified to change the context.params?

**Comment by acorcutt** [comment]
I've just added cypress to the example there is an undocumented option to make *.localhost work in tests https://github.com/cypress-io/cypress/issues/1488#issuecomment-396435553

**Comment by izziaraffaele** [comment]
Awesome! Maybe we can add the following on the readme as well

> On macOS you can just use a subdomain to localhost e.g. http://a.localhost:3000/ http://b.localhost:3000/ or add domains to your /etc/hosts file.
